version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: uwsgi --ini /etc/uwsgi.ini
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: