# Generated by Django 3.2.8 on 2021-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('posts', '0002_question_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='unliked',
            field=models.ManyToManyField(blank=True, related_name='a_unlikes', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='unliked',
            field=models.ManyToManyField(blank=True, related_name='q_unlikes', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='chosen_as_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
