# Generated by Django 3.2.8 on 2021-10-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211029_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
